# ~/.bash_aliases

alias 'ls'='exa'
alias 'cat'='bat'

alias mvnci='mvn clean install'
alias mvni='mvn install'


alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'
