# ~/.bash_aliases

# some more ls aliases
alias ll='ls -alF'
alias la='ls --all'
alias l='ls -F'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

alias 'ls'='exa --time-style long-iso'
alias 'cat'='bat'

alias mvnci='mvn clean install'
alias mvni='mvn install'


alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'
